// Fonte única de dados de todos os serviços da Santos Refrigeração.
// Cada página de serviço lê o seu objeto por slug. Mantém SEO e manutenção simples.
window.SERVICES_DATA = {
  'camara-fria': {
    slug: 'camara-fria',
    title: 'Câmara fria',
    icon: 'warehouse',
    eyebrow: 'Câmara fria',
    metaTitle: 'Conserto de câmara fria e frigorífica no Rio | Santos Refrigeração',
    metaDescription: 'Instalação, manutenção preventiva e corretiva de câmaras frias e frigoríficos comerciais no Rio de Janeiro e Grande Rio. Atendimento rápido, orçamento sem compromisso.',
    heroTitle: 'Instalação e manutenção de câmara fria no Rio e Grande Rio',
    highlight: 'câmara fria',
    heroLead: 'A instalação e a manutenção de câmaras frias exigem alta especialização técnica para assegurar a conservação ideal das mercadorias, a eficiência energética e a integridade do sistema. Seja em novos projetos ou em equipamentos em funcionamento, cada detalhe impacta diretamente o consumo elétrico e a durabilidade da sua câmara.',
    heroImageLabel: 'Foto da câmara fria / serviço',
    servicesTitle: 'Tudo o que a sua câmara fria precisa',
    intro: [
      'A montagem de uma câmara frigorífica de alto desempenho segue etapas estruturadas: começamos pelo estudo da carga térmica — tipo de produto (resfriado ou congelado), espaço disponível e dimensionamento exato do motor —, seguido do esquadrejamento e nivelamento da base, do isolamento térmico com painéis modulares isotérmicos de alta densidade (EPS, PUR ou PIR) e da fixação técnica das unidades evaporadora e condensadora.',
      'Na sequência, executamos a parte elétrica e hidráulica: tubulações em cobre, resistência de dreno (essencial em câmaras de congelados), válvula de expansão e quadro de comando. O fechamento é feito com vedação de silicone nas juntas, cantoneiras e perfis, mitigando infiltrações de umidade e ar quente.',
      'Na manutenção preventiva programada, limpamos o condensador (sujeira na unidade externa eleva a pressão e faz o motor desarmar ou queimar), inspecionamos as gaxetas de vedação das portas, monitoramos o fluido refrigerante em busca de microvazamentos e testamos drenos e resistências. Na corretiva, resolvemos emergências: ajuste de parâmetros do controlador digital, substituição de compressores, ventiladores e contatores, e reparo de painéis ou vedação avariados — sempre com diagnóstico e preço fechado antes de começar.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Projeto e instalação completa de câmara fria',
      'Estudo de carga térmica e dimensionamento do motor',
      'Montagem de painéis isotérmicos (EPS, PUR e PIR)',
      'Instalação de evaporadora e condensadora',
      'Parte elétrica: quadro de comando e resistência de dreno',
      'Manutenção preventiva programada',
      'Manutenção corretiva de emergência',
      'Limpeza técnica do condensador',
      'Inspeção e troca de gaxetas de vedação',
      'Verificação de gás e caça a microvazamentos',
      'Troca de compressor, ventiladores e contatores',
      'Ajuste de parâmetros do controlador digital',
      'Reparo de isolamento e substituição de painéis',
      'Contrato de manutenção regular',
    ],
    signsTitle: 'Sua câmara fria pode estar pedindo socorro',
    signs: [
      ['snowflake', 'Gelo em excesso', 'Formação excessiva de gelo nas paredes ou no evaporador indica falha de dreno ou vedação.'],
      ['volume-2', 'Ruídos anômalos', 'Barulhos estranhos vindos do compressor externo são sinal de desgaste.'],
      ['thermometer-sun', 'Não atinge a temperatura', 'Demora excessiva ou incapacidade de chegar à temperatura configurada no painel.'],
      ['zap', 'Picos na conta de luz', 'Oscilações constantes e consumo elevado apontam perda de eficiência térmica.'],
      ['door-open', 'Porta que não veda', 'Gaxeta ressecada deixa o frio escapar e força o motor a trabalhar mais.'],
      ['alert-triangle', 'Motor desarmando', 'Desligamentos frequentes costumam ser condensador sujo ou pressão alta.'],
    ],
    ctaTitle: 'Sua câmara fria parou? Conte conosco agora.',
    waMessage: 'Olá! Preciso de atendimento para CÂMARA FRIA. Podem me passar um orçamento?',
    faqTitle: 'Dúvidas sobre câmara fria',
    faq: [
      ['Como funciona a instalação de uma câmara fria do zero?', 'Seguimos etapas estruturadas: estudo da carga térmica e do tipo de produto (resfriado ou congelado), dimensionamento do motor, esquadrejamento e nivelamento da base, montagem dos painéis isotérmicos, fixação das unidades evaporadora e condensadora, parte elétrica e hidráulica, e vedação final com silicone. Você recebe o projeto e o preço fechado antes de começar.'],
      ['Qual a diferença entre câmara para resfriados e para congelados?', 'A finalidade define o projeto: resfriamento de bebidas e laticínios trabalha em temperaturas positivas; congelamento de carnes exige temperaturas negativas, motor mais robusto, isolamento reforçado e resistência de dreno para evitar congelamento interno. Por isso o dimensionamento correto é essencial.'],
      ['De quanto em quanto tempo fazer a manutenção preventiva?', 'Recomendamos visitas programadas periódicas, com limpeza do condensador, inspeção de gaxetas, verificação do fluido refrigerante e teste de drenos. O condensador sujo é a principal causa de motor desarmando ou queimando em dias quentes — a preventiva evita a parada e reduz a conta de luz.'],
      ['Minha câmara não atinge a temperatura. O que pode ser?', 'As causas mais comuns são parâmetros desajustados no controlador digital, gás refrigerante baixo por microvazamento, condensador sujo ou gaxetas de vedação ressecadas. Fazemos o diagnóstico medindo pressão e temperatura para corrigir a causa real, não só o sintoma.'],
      ['Vocês fazem reforma e contrato de manutenção regular?', 'Sim. Atendemos instalação do zero, reforma de câmaras existentes (substituição de painéis, readequação de vedação, modernização do sistema) e contratos de manutenção regular com visitas programadas — ideal para quem não pode ter parada no estoque.'],
    ],
  },

  'chopeiras': {
    slug: 'chopeiras',
    title: 'Chopeiras',
    icon: 'beer',
    eyebrow: 'Chopeiras',
    metaTitle: 'Manutenção de chopeira no Rio de Janeiro | Santos Refrigeração',
    metaDescription: 'Instalação, manutenção e higienização de chopeiras para bares, restaurantes e eventos no Rio e Grande Rio. Chopp sempre gelado e cremoso. Orçamento sem compromisso.',
    heroTitle: 'Manutenção e instalação de chopeira no Rio e Grande Rio',
    highlight: 'chopeira',
    heroLead: 'Especialistas em chopeiras comerciais, realizamos instalação, manutenção preventiva e corretiva, higienização e regulagem completa do sistema de tiragem. Atendemos bares, restaurantes, distribuidoras, eventos e operações de delivery, garantindo o máximo desempenho do equipamento, a qualidade do chopp servido e a continuidade da sua operação.',
    heroImageLabel: 'Chopeira torre — serviço Santos Refrigeração',
    gallery: ['assets/opt-d0.webp','assets/opt-d1.webp','assets/opt-d2.webp','assets/opt-d3.webp'],
    servicesTitle: 'Sua chopeira sempre pronta para o movimento',
    intro: [
      'Atendemos chopeiras de bares, restaurantes, distribuidoras e eventos. Da instalação à manutenção corretiva, deixamos a tiragem no ponto certo e a temperatura ideal para o chopp render.',
      'Trabalhamos em todo o sistema de tiragem: refrigeração da torre e do banho de gelo, regulagem de pressão de CO₂, vazão e temperatura da serpentina, além da assepsia e sanitização periódica das linhas — etapa essencial para preservar o sabor e a qualidade do chopp. Também executamos projetos de instalação, montagem de chopeiras a gelo e de beertrucks, dimensionando o equipamento conforme o volume e o layout do seu ponto de venda.',
      'Para quem trabalha com alto giro, oferecemos contratos de manutenção preventiva e corretiva, inclusive para operações de delivery de chopp, com visitas programadas que evitam paradas no movimento. Você recebe o diagnóstico e o preço fechado antes de começar. Trabalho limpo, rápido e com garantia no serviço.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Manutenção e instalação de chopeiras',
      'Assepsia / Sanitização',
      'Revisão',
      'Projetos de instalação para chopeira',
      'Montagem de chopeiras a gelo',
      'Montagem e instalação de beertruck',
      'Contrato de manutenção preventiva e corretiva para chopeira',
      'Contrato de manutenção para empresa de delivery de chopp',
      'Instalação de chopeira nova',
      'Manutenção preventiva e corretiva',
      'Higienização de linhas e serpentina',
      'Regulagem de pressão e gás (CO₂)',
      'Troca de compressor e peças',
      'Ajuste de temperatura e tiragem',
    ],
    signsTitle: 'Sinais de que a chopeira precisa de atenção',
    signs: [
      ['thermometer-sun', 'Chopp saindo quente', 'A chopeira não gela como deveria e o chopp perde qualidade.'],
      ['wind', 'Muito chuvisco', 'Excesso de espuma e chuvisco indicam pressão ou temperatura erradas.'],
      ['droplets', 'Gosto alterado', 'Sabor estranho costuma ser falta de higienização das linhas.'],
      ['volume-2', 'Ruído no motor', 'Barulho fora do normal é sinal de desgaste do compressor.'],
      ['gauge', 'Pressão desregulada', 'Chopp sem gás ou cilindro de CO₂ esvaziando rápido demais.'],
      ['droplet', 'Vazamento de chopp ou CO₂', 'Pingos nas conexões ou gás acabando antes da hora pedem revisão.'],
    ],
    ctaTitle: 'Chopeira parada é faturamento parado. Fale conosco.',
    waMessage: 'Olá! Preciso de atendimento para CHOPEIRA. Podem me passar um orçamento?',
    faqTitle: 'Dúvidas sobre chopeira',
    faq: [
      ['De quanto em quanto tempo a chopeira precisa de higienização?', 'O ideal é higienizar as linhas a cada 15 dias em locais de alto movimento e, no mínimo, uma vez por mês. A assepsia periódica remove resíduos e leveduras que se acumulam nas serpentinas e mangueiras, preservando o sabor do chopp e evitando contaminação. Operações de delivery e eventos exigem atenção redobrada.'],
      ['Vocês instalam chopeira nova e fazem o projeto?', 'Sim. Fazemos o projeto de instalação dimensionado para o seu espaço e volume de vendas, incluindo chopeiras a gelo e montagem de beertrucks. Avaliamos ponto de água, energia, posicionamento da torre e do cilindro de CO₂ para garantir a tiragem correta desde o primeiro dia.'],
      ['O chopp está saindo com muita espuma (chuvisco). O que pode ser?', 'Excesso de espuma e chuvisco geralmente indicam pressão de CO₂ desregulada, temperatura acima do ideal ou linha suja. Fazemos o diagnóstico medindo pressão e temperatura para identificar a causa real e ajustar o sistema — em vez de só tratar o sintoma.'],
      ['Atendem bares, eventos e delivery de chopp?', 'Atendemos bares, restaurantes, distribuidoras, eventos e operações de delivery em todo o Rio e Grande Rio. Para quem tem alto giro, oferecemos contratos de manutenção preventiva com visitas programadas, evitando paradas no movimento.'],
      ['Qual o prazo de atendimento e vocês dão garantia?', 'Trabalhamos com atendimento ágil e, na maioria dos casos, resolvemos na primeira visita. Você recebe o diagnóstico e o preço fechado antes de começar, sem surpresa na conta, e todo serviço tem garantia.'],
    ],
  },

  'gela-caneca': {
    slug: 'gela-caneca',
    title: 'Gela Caneca',
    icon: 'glass-water',
    eyebrow: 'Gela Caneca',
    metaTitle: 'Conserto de gela caneca no Rio de Janeiro | Santos Refrigeração',
    metaDescription: 'Manutenção, conserto e instalação de gela caneca para bares e restaurantes no Rio e Grande Rio. Canecas sempre congeladas. Orçamento sem compromisso.',
    heroTitle: 'Manutenção e conserto de gela caneca no Rio e Grande Rio',
    highlight: 'gela caneca',
    heroLead: 'Especialistas em gela caneca, cuidamos da instalação, manutenção preventiva e corretiva e do sistema de refrigeração que mantém as canecas na temperatura de congelamento. Atendemos bares, restaurantes, distribuidoras e eventos, garantindo a camada de gelo perfeita e a apresentação que valoriza o seu chopp e a sua cerveja.',
    heroImageLabel: 'Foto do gela caneca / serviço',
    servicesTitle: 'Seu gela caneca sempre no ponto',
    intro: [
      'O gela caneca trabalha com temperaturas negativas e ciclo contínuo: o compressor precisa vencer a abertura constante do equipamento sem perder rendimento. Fazemos a instalação dimensionada para o seu volume, o nivelamento correto e a regulagem do termostato para que as canecas saiam sempre com a camada de gelo uniforme.',
      'Na manutenção preventiva verificamos a carga de gás refrigerante, testamos o compressor e o ventilador, limpamos o condensador (sujeira eleva a pressão e derruba o congelamento), inspecionamos as borrachas de vedação e fazemos o degelo técnico para evitar acúmulo excessivo de gelo interno.',
      'Na corretiva resolvemos as falhas mais comuns — equipamento que não congela, formação exagerada de gelo, ruído no motor e alto consumo — com troca de compressor, recarga de gás, substituição de termostato e componentes elétricos. Você recebe o diagnóstico e o preço fechado antes de começar, com garantia no serviço.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Instalação e nivelamento de gela caneca',
      'Manutenção preventiva programada',
      'Manutenção corretiva de emergência',
      'Recarga e troca de gás refrigerante',
      'Troca de compressor',
      'Limpeza técnica do condensador',
      'Degelo técnico e higienização interna',
      'Substituição de termostato e controle de temperatura',
      'Troca de borrachas e vedações',
      'Reparo de ventilador e parte elétrica',
      'Ajuste e calibração da camada de gelo',
      'Contrato de manutenção regular',
    ],
    signsTitle: 'Sinais de que o gela caneca precisa de atenção',
    signs: [
      ['thermometer-sun', 'Não congela', 'As canecas saem sem a camada de gelo característica.'],
      ['snowflake', 'Gelo em excesso', 'Acúmulo espesso de gelo interno reduz o espaço e o rendimento.'],
      ['volume-2', 'Ruído no motor', 'Barulho estranho indica desgaste do compressor.'],
      ['zap', 'Conta de luz alta', 'Consumo elevado costuma ser condensador sujo ou gás baixo.'],
      ['clock', 'Demora para congelar', 'A caneca leva tempo demais para atingir o ponto.'],
      ['power', 'Desliga sozinho', 'Desarmes frequentes apontam falha elétrica ou superaquecimento.'],
    ],
    ctaTitle: 'Gela caneca parado? Fale conosco agora.',
    waMessage: 'Olá! Preciso de atendimento para GELA CANECA. Podem me passar um orçamento?',
    faqTitle: 'Dúvidas sobre gela caneca',
    faq: [
      ['Por que o gela caneca parou de congelar as canecas?', 'As causas mais comuns são gás refrigerante baixo por microvazamento, condensador sujo, termostato desregulado ou compressor com desgaste. Medimos pressão e temperatura para identificar a causa real e corrigir só o que precisa.'],
      ['Com que frequência devo fazer manutenção?', 'Recomendamos revisão preventiva periódica, com limpeza do condensador, verificação de gás e degelo técnico. Em locais de alto movimento, a preventiva evita a parada no fim de semana e mantém o consumo de energia sob controle.'],
      ['Formou muito gelo dentro do equipamento. É problema?', 'Sim. O excesso de gelo indica falha na vedação, no degelo ou umidade entrando no equipamento. Além de reduzir o espaço útil, força o motor e aumenta a conta de luz. Fazemos o degelo técnico e corrigimos a causa.'],
      ['Vocês instalam gela caneca novo?', 'Sim. Fazemos a instalação com nivelamento correto, avaliação do ponto elétrico e regulagem inicial da temperatura, deixando o equipamento pronto para operar com a camada de gelo no ponto.'],
    ],
  },

  'ar-condicionado': {
    slug: 'ar-condicionado',
    title: 'Ar condicionado',
    icon: 'air-vent',
    eyebrow: 'Ar condicionado',
    metaTitle: 'Instalação e manutenção de ar condicionado no Rio | Santos Refrigeração',
    metaDescription: 'Instalação, limpeza e manutenção de ar condicionado comercial e residencial no Rio e Grande Rio. Ambiente climatizado, conta de luz sob controle. Orçamento sem compromisso.',
    heroTitle: 'Instalação e manutenção de ar condicionado no Rio e Grande Rio',
    highlight: 'ar condicionado',
    heroLead: 'Conforto térmico e conta de luz sob controle. Fazemos instalação, limpeza, higienização e manutenção preventiva e corretiva de ar condicionado comercial e residencial — split, cassete, piso-teto e sistemas de maior porte — com técnicos especializados, carga de gás correta e atendimento em todo o Rio e Grande Rio.',
    heroImageLabel: 'Foto do ar condicionado / serviço',
    servicesTitle: 'Ar condicionado gelando e econômico',
    intro: [
      'Uma instalação bem-feita começa pelo dimensionamento correto de BTUs para o ambiente e pela posição adequada das unidades interna (evaporadora) e externa (condensadora). Executamos a passagem de tubulação de cobre, o vácuo na linha, a carga de gás na medida certa e o dreno com caimento correto — detalhes que definem o rendimento e a durabilidade do aparelho.',
      'Na manutenção preventiva fazemos a limpeza e higienização completa de filtros, serpentinas e turbina, verificamos a pressão e a carga de gás, testamos o dreno e medimos o consumo. Ar condicionado limpo gela mais rápido, consome menos energia e evita mofo e mau cheiro no ambiente.',
      'Na corretiva resolvemos aparelho que não gela, vazamento de água, ruído, cheiro ao ligar e desarme frequente — com recarga de gás, reparo de vazamento, troca de capacitor, placa e demais componentes. Diagnóstico e preço fechado antes de começar, com garantia no serviço. Atendemos comércio e residência.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Instalação de ar condicionado split e comercial',
      'Dimensionamento de BTUs para o ambiente',
      'Limpeza e higienização completa',
      'Manutenção preventiva programada',
      'Manutenção corretiva de emergência',
      'Recarga e reparo de vazamento de gás',
      'Passagem de tubulação de cobre e dreno',
      'Troca de capacitor, placa e componentes',
      'Reparo de ruído e vibração',
      'Desentupimento e reparo de dreno',
      'Avaliação de eficiência e consumo',
      'Atendimento residencial e comercial',
      'Contrato de manutenção regular',
    ],
    signsTitle: 'Sinais de que o ar condicionado precisa de atenção',
    signs: [
      ['thermometer-sun', 'Não gela direito', 'O ambiente não atinge a temperatura desejada.'],
      ['droplets', 'Vazamento de água', 'Pingos ou poças indicam dreno entupido ou mal instalado.'],
      ['wind', 'Cheiro ao ligar', 'Odor de mofo pede limpeza e higienização da serpentina.'],
      ['volume-2', 'Barulho ou vibração', 'Ruído alto aponta desgaste do ventilador ou da turbina.'],
      ['zap', 'Conta de luz alta', 'Consumo elevado costuma ser falta de manutenção ou gás baixo.'],
      ['power', 'Desarma sozinho', 'Desligamentos frequentes indicam capacitor, placa ou sobrecarga.'],
    ],
    ctaTitle: 'Ar condicionado com problema? Fale conosco.',
    waMessage: 'Olá! Preciso de atendimento para AR CONDICIONADO. Podem me passar um orçamento?',
    faqTitle: 'Dúvidas sobre ar condicionado',
    faq: [
      ['De quanto em quanto tempo fazer a limpeza do ar condicionado?', 'Para uso residencial, o ideal é a cada 6 meses; em ambiente comercial de uso intenso, a cada 3 meses. A limpeza de filtros e serpentina mantém o gelo eficiente, reduz o consumo de energia e evita mofo e alergias.'],
      ['Meu ar condicionado não está gelando. O que pode ser?', 'Normalmente é gás baixo por vazamento, filtro e serpentina sujos, capacitor fraco ou dimensionamento incorreto para o ambiente. Medimos a pressão e a temperatura para identificar a causa e corrigir de forma definitiva, não só recarregar gás.'],
      ['Vocês atendem residência ou só comércio?', 'Atendemos os dois. Fazemos instalação e manutenção de ar condicionado comercial (lojas, escritórios, restaurantes, indústrias) e residencial (apartamentos e casas) em todo o Rio e Grande Rio.'],
      ['Está pingando água da unidade interna. É grave?', 'Quase sempre é o dreno entupido ou sem caimento, ou gelo se formando na serpentina por falta de limpeza. Fazemos o desentupimento e a correção do dreno e higienizamos o aparelho para resolver.'],
      ['Vocês fazem a instalação completa, com tubulação?', 'Sim. Fazemos a instalação do zero com dimensionamento de BTUs, passagem de tubulação de cobre, vácuo na linha, carga de gás e dreno — deixando o aparelho pronto e com garantia.'],
    ],
  },

  'geladeira-comercial': {
    slug: 'geladeira-comercial',
    title: 'Geladeira comercial',
    icon: 'refrigerator',
    eyebrow: 'Geladeira comercial',
    metaTitle: 'Conserto de geladeira comercial no Rio | Santos Refrigeração',
    metaDescription: 'Conserto e manutenção de geladeira e refrigerador comercial ou industrial no Rio e Grande Rio. Sempre gelando, sem perda de produto. Orçamento sem compromisso.',
    heroTitle: 'Conserto e manutenção de geladeira comercial no Rio e Grande Rio',
    highlight: 'geladeira comercial',
    heroLead: 'Geladeira parada é produto estragado e prejuízo. Fazemos conserto, manutenção preventiva e corretiva e instalação de geladeiras e refrigeradores comerciais e industriais — expositores, verticais, de encosto e câmaras compactas — mantendo a temperatura estável e a conta de luz sob controle em todo o Rio e Grande Rio.',
    heroImageLabel: 'Foto da geladeira comercial / serviço',
    servicesTitle: 'Sua geladeira comercial sempre gelando',
    intro: [
      'Atendemos geladeiras e refrigeradores comerciais e industriais de mercados, padarias, açougues, restaurantes e lojas. O ponto crítico desses equipamentos é a estabilidade da temperatura: portas que abrem o tempo todo, ambiente quente e sobrecarga de produtos exigem compressor e vedação em perfeito estado.',
      'Na manutenção preventiva limpamos o condensador (a principal causa de motor superaquecido e desarme), verificamos a carga de gás e microvazamentos, testamos termostato e controlador, inspecionamos as gaxetas das portas e fazemos a limpeza técnica do sistema. Assim a temperatura se mantém e o consumo de energia cai.',
      'Na corretiva de emergência resolvemos geladeira que não gela, excesso de gelo, vazamento de água, ruído e alto consumo — com troca de compressor, recarga de gás, reparo de termostato, vedação e parte elétrica. Diagnóstico e preço fechado antes do serviço, trocando só o necessário, com garantia no reparo.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Conserto corretivo de emergência',
      'Manutenção preventiva programada',
      'Instalação de geladeira e refrigerador comercial',
      'Troca de compressor',
      'Recarga e reparo de vazamento de gás',
      'Limpeza técnica do condensador',
      'Reparo e troca de termostato e controlador',
      'Substituição de gaxetas e vedação das portas',
      'Reparo de ventilador e parte elétrica',
      'Ajuste e calibração de temperatura',
      'Degelo técnico e higienização',
      'Avaliação de eficiência e consumo',
      'Contrato de manutenção regular',
    ],
    signsTitle: 'Sinais de que a geladeira precisa de atenção',
    signs: [
      ['thermometer-sun', 'Não gela o suficiente', 'A temperatura interna não se mantém e o produto sofre.'],
      ['snowflake', 'Excesso de gelo', 'Camada espessa de gelo indica falha no degelo ou na vedação.'],
      ['droplets', 'Vazamento de água', 'Poças no piso apontam dreno entupido ou gelo derretendo.'],
      ['volume-2', 'Motor barulhento', 'Ruído fora do normal é sinal de desgaste do compressor.'],
      ['zap', 'Conta de luz alta', 'Consumo elevado costuma ser condensador sujo ou gás baixo.'],
      ['door-open', 'Porta que não veda', 'Gaxeta ressecada deixa o frio escapar e força o motor.'],
    ],
    ctaTitle: 'Geladeira comercial parada? Fale conosco agora.',
    waMessage: 'Olá! Preciso de atendimento para GELADEIRA COMERCIAL. Podem me passar um orçamento?',
    faqTitle: 'Dúvidas sobre geladeira comercial',
    faq: [
      ['Minha geladeira comercial não está gelando. O que fazer?', 'As causas mais comuns são gás baixo por vazamento, condensador sujo, termostato desregulado ou compressor com desgaste. Fazemos o diagnóstico medindo pressão e temperatura para corrigir a causa real e evitar perda de mercadoria.'],
      ['Vale a pena consertar ou é melhor trocar?', 'Depende do estado do compressor e da estrutura. Fazemos uma avaliação honesta: em muitos casos a troca de compressor, gás ou termostato devolve anos de vida útil por um custo bem menor que o de um equipamento novo. Você decide com o diagnóstico e o preço em mãos.'],
      ['De quanto em quanto tempo fazer manutenção preventiva?', 'Recomendamos revisões periódicas, principalmente a limpeza do condensador, que é a maior causa de motor desarmando em dias quentes. A preventiva mantém a temperatura estável, evita a parada e reduz a conta de luz.'],
      ['Vocês atendem equipamento industrial?', 'Sim. Atendemos geladeiras e refrigeradores comerciais e industriais de todos os portes, incluindo expositores, câmaras compactas e sistemas de maior capacidade.'],
    ],
  },

  'balcao-refrigerado': {
    slug: 'balcao-refrigerado',
    title: 'Balcão refrigerado',
    icon: 'store',
    eyebrow: 'Balcão refrigerado',
    metaTitle: 'Conserto de balcão refrigerado no Rio | Santos Refrigeração',
    metaDescription: 'Conserto, manutenção e instalação de balcões e expositores refrigerados no Rio e Grande Rio. Produtos conservados e bem expostos. Orçamento sem compromisso.',
    heroTitle: 'Conserto e manutenção de balcão refrigerado no Rio e Grande Rio',
    highlight: 'balcão refrigerado',
    heroLead: 'O balcão refrigerado conserva e vende ao mesmo tempo — por isso precisa manter a temperatura certa com o produto bem exposto. Fazemos instalação, manutenção preventiva e corretiva e conserto de balcões e expositores refrigerados de padarias, lanchonetes, mercados, açougues e lojas em todo o Rio e Grande Rio.',
    heroImageLabel: 'Balcão refrigerado expositor',
    servicesTitle: 'Balcão refrigerado conservando e vendendo',
    intro: [
      'O balcão refrigerado tem um desafio específico: refrigerar com o vidro exposto e a abertura constante para atendimento. A cortina de ar, a vedação e a circulação interna precisam estar no ponto para conservar o produto sem embaçar o vidro nem estragar a mercadoria. Fazemos a instalação nivelada e a regulagem inicial completa.',
      'Na manutenção preventiva limpamos o condensador e a serpentina, verificamos a carga de gás, testamos o termostato e o sistema de circulação, inspecionamos as borrachas de vedação, a iluminação e o dreno. Balcão bem regulado conserva mais, embaça menos e gasta menos energia.',
      'Na corretiva resolvemos balcão que não conserva o produto, vidros embaçados, água acumulada, ruído e consumo alto — com troca de compressor, recarga de gás, reparo de vidros, vedação, iluminação e parte elétrica. Diagnóstico e preço fechado antes de começar, com garantia no serviço.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Instalação e nivelamento de balcão refrigerado',
      'Manutenção preventiva programada',
      'Manutenção corretiva de emergência',
      'Troca de compressor',
      'Recarga e reparo de vazamento de gás',
      'Limpeza técnica de condensador e serpentina',
      'Reparo de vidros, vedação e borrachas',
      'Reparo de iluminação e parte elétrica',
      'Reparo do sistema de circulação de ar',
      'Ajuste e calibração de temperatura',
      'Desentupimento e reparo de dreno',
      'Contrato de manutenção regular',
    ],
    signsTitle: 'Sinais de que o balcão precisa de atenção',
    signs: [
      ['thermometer-sun', 'Não conserva o produto', 'A temperatura não se mantém e a mercadoria estraga.'],
      ['droplets', 'Embaçamento ou água', 'Vidros embaçados ou poças indicam falha na refrigeração ou no dreno.'],
      ['snowflake', 'Excesso de gelo', 'Gelo na serpentina reduz a circulação e o rendimento.'],
      ['volume-2', 'Ruído no motor', 'Barulho estranho é sinal de desgaste do compressor.'],
      ['zap', 'Conta de luz alta', 'Consumo elevado costuma ser falta de manutenção ou gás baixo.'],
      ['lightbulb', 'Iluminação falhando', 'Lâmpadas queimadas prejudicam a exposição e a venda.'],
    ],
    ctaTitle: 'Balcão refrigerado com problema? Fale conosco.',
    waMessage: 'Olá! Preciso de atendimento para BALCÃO REFRIGERADO. Podem me passar um orçamento?',
    faqTitle: 'Dúvidas sobre balcão refrigerado',
    faq: [
      ['Por que o vidro do balcão fica embaçado?', 'O embaçamento aparece quando a temperatura ou a circulação de ar estão desreguladas, a vedação está gasta ou a umidade está alta. Regulamos o sistema e corrigimos a vedação para o produto ficar bem exposto e visível.'],
      ['O balcão não está conservando o produto. O que pode ser?', 'Normalmente é gás baixo por vazamento, condensador sujo, termostato desregulado ou compressor com desgaste. Medimos pressão e temperatura para achar a causa real e corrigir de forma definitiva.'],
      ['Vocês trocam vidro e iluminação do balcão?', 'Sim. Além da parte de refrigeração, fazemos reparo de vidros, borrachas de vedação e iluminação — itens que afetam tanto a conservação quanto a apresentação da vitrine.'],
      ['Fazem contrato de manutenção para o balcão?', 'Sim. O contrato de manutenção regular com visitas programadas é ideal para padarias e mercados que não podem ter parada, mantendo o balcão sempre no ponto e reduzindo emergências.'],
    ],
  },

  'ilha-de-congelados': {
    slug: 'ilha-de-congelados',
    title: 'Ilha de congelados',
    icon: 'boxes',
    eyebrow: 'Ilha de congelados',
    metaTitle: 'Conserto de ilha de congelados no Rio | Santos Refrigeração',
    metaDescription: 'Conserto, manutenção e instalação de ilhas de congelados e expositores no Rio e Grande Rio. Congelados conservados e bem expostos. Orçamento sem compromisso.',
    heroTitle: 'Conserto e manutenção de ilha de congelados no Rio e Grande Rio',
    highlight: 'ilha de congelados',
    heroLead: 'A ilha de congelados precisa manter temperatura negativa mesmo aberta o dia todo. Fazemos instalação, manutenção preventiva e corretiva e conserto de ilhas e expositores de congelados de mercados, açougues, sorveterias e distribuidoras, conservando o produto sem desperdício em todo o Rio e Grande Rio.',
    heroImageLabel: 'Foto da ilha de congelados / serviço',
    servicesTitle: 'Ilha de congelados sempre na temperatura certa',
    intro: [
      'A ilha de congelados trabalha com temperaturas negativas e acesso aberto ao público, o que exige compressor robusto, isolamento e degelo eficientes. Fazemos a instalação nivelada, a avaliação do ponto elétrico e a regulagem para o produto se manter congelado sem formar gelo em excesso.',
      'Na manutenção preventiva limpamos o condensador, verificamos a carga de gás e microvazamentos, testamos o termostato e o sistema de degelo, inspecionamos a vedação e fazemos o degelo técnico. O degelo em dia é o que garante temperatura estável e menor consumo de energia.',
      'Na corretiva resolvemos ilha que não mantém o congelado, excesso de gelo, ruído e alto consumo — com troca de compressor, recarga de gás, reparo de termostato, sistema de degelo e parte elétrica. Diagnóstico e preço fechado antes de começar, trocando só o necessário, com garantia no serviço.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Instalação e nivelamento de ilha de congelados',
      'Manutenção preventiva programada',
      'Manutenção corretiva de emergência',
      'Troca de compressor',
      'Recarga e reparo de vazamento de gás',
      'Limpeza técnica do condensador',
      'Reparo do sistema de degelo automático',
      'Reparo e troca de termostato e controlador',
      'Substituição de vedação',
      'Reparo de ventilador e parte elétrica',
      'Ajuste e calibração de temperatura',
      'Contrato de manutenção regular',
    ],
    signsTitle: 'Sinais de que a ilha precisa de atenção',
    signs: [
      ['thermometer-sun', 'Não mantém congelado', 'Os produtos amolecem ou descongelam parcialmente.'],
      ['snowflake', 'Excesso de gelo', 'Camada espessa de gelo reduz a eficiência e o espaço.'],
      ['droplets', 'Água acumulada', 'Poças indicam degelo com falha ou dreno entupido.'],
      ['volume-2', 'Motor barulhento', 'Ruído fora do normal indica desgaste do compressor.'],
      ['zap', 'Conta de luz alta', 'Consumo elevado costuma ser condensador sujo ou degelo com defeito.'],
      ['power', 'Desarma sozinho', 'Desligamentos frequentes apontam sobrecarga ou falha elétrica.'],
    ],
    ctaTitle: 'Ilha de congelados com problema? Fale conosco.',
    waMessage: 'Olá! Preciso de atendimento para ILHA DE CONGELADOS. Podem me passar um orçamento?',
    faqTitle: 'Dúvidas sobre ilha de congelados',
    faq: [
      ['A ilha está formando muito gelo. Qual a causa?', 'Excesso de gelo quase sempre é falha no sistema de degelo, vedação gasta ou umidade entrando no equipamento. Além de ocupar espaço, reduz o frio e aumenta o consumo. Fazemos o degelo técnico e corrigimos a origem do problema.'],
      ['Os produtos estão amolecendo. É perigoso?', 'Sim, porque compromete a segurança do alimento. Costuma ser gás baixo por vazamento, condensador sujo ou termostato desregulado. Medimos pressão e temperatura para restabelecer a temperatura correta com rapidez.'],
      ['De quanto em quanto tempo fazer manutenção?', 'Recomendamos revisões periódicas com limpeza do condensador e verificação do degelo e do gás. A preventiva evita a parada, mantém o produto seguro e reduz a conta de luz.'],
      ['Vocês instalam ilha nova?', 'Sim. Fazemos a instalação com nivelamento, avaliação do ponto elétrico e regulagem inicial, deixando o equipamento pronto para conservar os congelados.'],
    ],
  },

  'ultra-freezer': {
    slug: 'ultra-freezer',
    title: 'Ultra freezer',
    icon: 'thermometer-snowflake',
    eyebrow: 'Ultra freezer',
    metaTitle: 'Conserto de ultra freezer no Rio de Janeiro | Santos Refrigeração',
    metaDescription: 'Conserto e manutenção de ultra freezer e equipamentos de baixa temperatura no Rio e Grande Rio. Precisão e confiabilidade. Orçamento sem compromisso.',
    heroTitle: 'Conserto e manutenção de ultra freezer no Rio e Grande Rio',
    highlight: 'ultra freezer',
    heroLead: 'Ultra freezer exige precisão de temperatura e confiabilidade total — não há margem para oscilação com o seu conteúdo. Fazemos manutenção preventiva e corretiva e conserto especializado de ultra freezers e equipamentos de baixa temperatura de laboratórios, clínicas, indústrias e comércios em todo o Rio e Grande Rio.',
    heroImageLabel: 'Foto do ultra freezer / serviço',
    servicesTitle: 'Ultra freezer com a precisão que você precisa',
    intro: [
      'O ultra freezer opera em temperaturas muito baixas (frequentemente abaixo de -40 °C) e protege conteúdos sensíveis e de alto valor. Isso exige compressores em cascata, isolamento reforçado e controle eletrônico preciso — qualquer oscilação pode comprometer todo o conteúdo, por isso o acompanhamento técnico é essencial.',
      'Na manutenção preventiva verificamos a carga de gás e microvazamentos, testamos os estágios de compressão, o controle eletrônico e os alarmes, limpamos o condensador e inspecionamos a vedação. Monitoramos a estabilidade da temperatura para garantir que o equipamento se mantenha na faixa programada.',
      'Na corretiva atuamos com urgência: equipamento que não atinge a temperatura, oscilações, alarme disparado, excesso de gelo ou ruído — com troca de compressor, recarga de gás, reparo de controle eletrônico, vedação e parte elétrica. Diagnóstico e preço fechado antes de começar, com garantia no reparo e prioridade no atendimento.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Manutenção preventiva programada',
      'Manutenção corretiva de emergência',
      'Diagnóstico de baixa temperatura e estabilidade',
      'Troca de compressor (sistema em cascata)',
      'Recarga e reparo de vazamento de gás',
      'Reparo de controle eletrônico e alarmes',
      'Limpeza técnica do condensador',
      'Substituição de vedação e componentes',
      'Reparo de parte elétrica',
      'Ajuste e calibração de temperatura',
      'Monitoramento de desempenho',
      'Contrato de manutenção regular',
    ],
    signsTitle: 'Sinais de que o ultra freezer precisa de atenção',
    signs: [
      ['thermometer-sun', 'Não atinge a temperatura', 'O equipamento não chega à baixa temperatura programada.'],
      ['alert-triangle', 'Alarme ou oscilação', 'Variações de temperatura colocam o conteúdo em risco.'],
      ['snowflake', 'Excesso de gelo', 'Acúmulo de gelo compromete o desempenho e o espaço.'],
      ['volume-2', 'Ruído ou vibração', 'Barulho fora do normal indica desgaste de componentes.'],
      ['zap', 'Consumo elevado', 'Aumento no consumo aponta perda de eficiência do sistema.'],
      ['power', 'Desarma sozinho', 'Desligamentos comprometem conteúdo de alto valor.'],
    ],
    ctaTitle: 'Ultra freezer com problema? Fale conosco agora.',
    waMessage: 'Olá! Preciso de atendimento para ULTRA FREEZER. Podem me passar um orçamento?',
    faqTitle: 'Dúvidas sobre ultra freezer',
    faq: [
      ['O ultra freezer parou de atingir a temperatura. O que fazer?', 'Como o conteúdo costuma ser sensível, tratamos como urgência. As causas mais comuns são gás baixo por vazamento, falha em um dos estágios de compressão, controle eletrônico desregulado ou condensador sujo. Fazemos o diagnóstico completo para restabelecer a faixa correta.'],
      ['Com que frequência fazer manutenção preventiva?', 'Por se tratar de equipamento crítico, recomendamos manutenção preventiva periódica e, quando possível, monitoramento da estabilidade da temperatura. A preventiva reduz drasticamente o risco de perda do conteúdo.'],
      ['Vocês atendem laboratórios e clínicas?', 'Sim. Atendemos ultra freezers e equipamentos de baixa temperatura de laboratórios, clínicas, indústrias e comércios, com diagnóstico técnico e garantia no serviço.'],
      ['O alarme do equipamento disparou. É grave?', 'O alarme sinaliza oscilação fora da faixa segura e deve ser tratado imediatamente. Atendemos com prioridade para identificar a causa — gás, compressão, controle ou vedação — e estabilizar a temperatura.'],
    ],
  },

  'refresqueira': {
    slug: 'refresqueira',
    title: 'Refresqueira',
    icon: 'cup-soda',
    eyebrow: 'Refresqueira',
    metaTitle: 'Conserto de refresqueira no Rio de Janeiro | Santos Refrigeração',
    metaDescription: 'Conserto, manutenção e instalação de refresqueiras para lanchonetes, eventos e comércios no Rio e Grande Rio. Suco gelado o dia todo. Orçamento sem compromisso.',
    heroTitle: 'Conserto e manutenção de refresqueira no Rio e Grande Rio',
    highlight: 'refresqueira',
    heroLead: 'Refresqueira parada é venda perdida em dia de calor. Fazemos instalação, manutenção preventiva e corretiva e conserto de refresqueiras de lanchonetes, padarias, eventos e comércios, mantendo o suco gelado e circulando bem o dia inteiro em todo o Rio e Grande Rio.',
    heroImageLabel: 'Foto da refresqueira / serviço',
    servicesTitle: 'Refresqueira sempre pronta para vender',
    intro: [
      'A refresqueira combina refrigeração e circulação: além de gelar, a bomba precisa manter o suco em movimento constante para dar a aparência e a temperatura que atraem o cliente. Fazemos a instalação nivelada, a avaliação do ponto elétrico e a regulagem para o equipamento render no movimento.',
      'Na manutenção preventiva verificamos a carga de gás, testamos o compressor e a bomba de circulação, limpamos o condensador, inspecionamos as borrachas de vedação e higienizamos o sistema — item essencial por se tratar de equipamento que trabalha com bebida.',
      'Na corretiva resolvemos refresqueira que sai com o suco quente, que não circula, com vazamento, ruído ou consumo alto — com troca de compressor, recarga de gás, reparo ou troca da bomba, substituição de borrachas e parte elétrica. Diagnóstico e preço fechado antes de começar, com garantia no serviço.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Instalação e nivelamento de refresqueira',
      'Manutenção preventiva programada',
      'Manutenção corretiva de emergência',
      'Troca de compressor',
      'Recarga e reparo de vazamento de gás',
      'Reparo e troca da bomba de circulação',
      'Limpeza técnica do condensador',
      'Higienização completa do sistema',
      'Substituição de borrachas e vedações',
      'Reparo de parte elétrica',
      'Ajuste e calibração de temperatura',
      'Contrato de manutenção regular',
    ],
    signsTitle: 'Sinais de que a refresqueira precisa de atenção',
    signs: [
      ['thermometer-sun', 'Suco saindo quente', 'O equipamento não gela como deveria.'],
      ['rotate-cw', 'Não circula o suco', 'A bomba parada deixa o líquido parado e sem aparência.'],
      ['droplets', 'Vazamento', 'Vazamentos pedem troca de borrachas e revisão do sistema.'],
      ['volume-2', 'Ruído no motor', 'Barulho estranho indica desgaste do compressor ou da bomba.'],
      ['zap', 'Conta de luz alta', 'Consumo elevado costuma ser condensador sujo ou gás baixo.'],
      ['power', 'Desliga sozinho', 'Desarmes frequentes apontam falha elétrica ou superaquecimento.'],
    ],
    ctaTitle: 'Refresqueira parada? Fale conosco agora.',
    waMessage: 'Olá! Preciso de atendimento para REFRESQUEIRA. Podem me passar um orçamento?',
    faqTitle: 'Dúvidas sobre refresqueira',
    faq: [
      ['A refresqueira não está gelando o suco. O que pode ser?', 'Geralmente é gás baixo por vazamento, condensador sujo, termostato desregulado ou compressor com desgaste. Medimos pressão e temperatura para identificar a causa e corrigir de forma definitiva.'],
      ['O suco parou de circular. Como resolver?', 'A circulação depende da bomba. Quando o suco fica parado, costuma ser a bomba travada ou com defeito. Fazemos o reparo ou a troca da bomba para o líquido voltar a circular com a aparência certa.'],
      ['Com que frequência higienizar a refresqueira?', 'Por trabalhar com bebida, a higienização deve ser frequente — recomendamos limpeza regular do reservatório e do sistema, além da manutenção preventiva periódica, para garantir sabor e segurança.'],
      ['Vocês atendem eventos?', 'Sim. Atendemos lanchonetes, padarias, comércios e eventos. Fazemos instalação, manutenção e conserto para o equipamento não falhar justamente no dia de maior movimento.'],
    ],
  },

  'adega-vinhos': {
    slug: 'adega-vinhos',
    title: 'Adega climatizada de vinhos',
    icon: 'wine',
    eyebrow: 'Adega climatizada',
    metaTitle: 'Manutenção de adega climatizada no Rio | Santos Refrigeração',
    metaDescription: 'Instalação, manutenção preventiva e corretiva de adegas climatizadas de vinhos para restaurantes, bares, adegas e residências no Rio e Grande Rio. Temperatura e umidade no ponto certo.',
    heroTitle: 'Manutenção e instalação de adega climatizada de vinhos no Rio e Grande Rio',
    highlight: 'adega climatizada',
    heroLead: 'A adega climatizada conserva o vinho na temperatura e na umidade ideais, protegendo aroma, sabor e valor de cada garrafa. Fazemos instalação, manutenção preventiva e corretiva e conserto de adegas de compressor e termoelétricas para restaurantes, bares, adegas comerciais e residências, com controle preciso e vibração reduzida em todo o Rio e Grande Rio.',
    heroImageLabel: 'Adega climatizada de vinhos — serviço Santos Refrigeração',
    servicesTitle: 'Sua adega de vinhos sempre no ponto',
    intro: [
      'A adega climatizada é um equipamento de precisão: além de gelar, precisa manter a temperatura estável (sem oscilações), a umidade controlada e a vibração mínima — fatores que preservam a rolha e a evolução do vinho. Trabalhamos com adegas de compressor e termoelétricas, de garrafeiras residenciais a expositores comerciais de grande capacidade.',
      'Na manutenção preventiva verificamos a carga de gás refrigerante e microvazamentos, testamos o compressor e o sistema de controle eletrônico, limpamos o condensador, inspecionamos as borrachas de vedação e a iluminação, e conferimos o sistema de umidade e a vedação da porta de vidro. Adega bem regulada mantém a temperatura estável, gasta menos energia e não deixa o vinho sofrer.',
      'Na corretiva resolvemos adega que não gela, que oscila de temperatura, com excesso de umidade ou condensação, ruído, vibração ou consumo alto — com troca de compressor, recarga de gás, reparo do controle eletrônico, iluminação, vedação e parte elétrica. Diagnóstico e preço fechado antes de começar, com garantia no serviço.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Instalação e nivelamento de adega climatizada',
      'Manutenção preventiva programada',
      'Manutenção corretiva de emergência',
      'Troca de compressor',
      'Recarga e reparo de vazamento de gás',
      'Reparo de sistema termoelétrico (pastilha Peltier)',
      'Limpeza técnica do condensador',
      'Reparo do controle eletrônico de temperatura',
      'Ajuste de umidade e vedação da porta de vidro',
      'Reparo de iluminação e parte elétrica',
      'Redução de vibração e ruído',
      'Contrato de manutenção regular',
    ],
    signsTitle: 'Sinais de que a sua adega precisa de atenção',
    signs: [
      ['thermometer-sun', 'Não gela ou oscila', 'A temperatura não se mantém estável e o vinho sofre.'],
      ['droplets', 'Umidade ou condensação', 'Excesso de água no vidro ou dentro indica falha de vedação ou umidade.'],
      ['volume-2', 'Ruído ou vibração', 'Barulho ou vibração excessiva prejudica o vinho e indica desgaste.'],
      ['zap', 'Conta de luz alta', 'Consumo elevado costuma ser condensador sujo ou gás baixo.'],
      ['door-open', 'Porta que não veda', 'A borracha ressecada deixa o frio escapar e força o equipamento.'],
      ['lightbulb', 'Iluminação falhando', 'Lâmpadas queimadas prejudicam a exposição das garrafas.'],
    ],
    ctaTitle: 'Sua adega de vinhos com problema? Fale conosco.',
    waMessage: 'Olá! Preciso de atendimento para ADEGA CLIMATIZADA DE VINHOS. Podem me passar um orçamento?',
    faqTitle: 'Dúvidas sobre adega climatizada de vinhos',
    faq: [
      ['Qual a diferença entre adega de compressor e termoelétrica?', 'A de compressor refrigera como uma geladeira, atinge temperaturas mais baixas e suporta maior capacidade e calor ambiente — ideal para uso comercial. A termoelétrica (pastilha Peltier) é mais silenciosa e com menos vibração, indicada para menores capacidades. Atendemos e consertamos os dois tipos.'],
      ['Minha adega não está mantendo a temperatura. O que pode ser?', 'As causas comuns são gás baixo por vazamento, condensador sujo, controle eletrônico desregulado, vedação da porta gasta ou, nas termoelétricas, falha na pastilha e no ventilador. Medimos e diagnosticamos para corrigir a causa real, não só o sintoma.'],
      ['Por que aparece condensação no vidro da adega?', 'A condensação surge quando a umidade e a temperatura estão desreguladas ou a vedação da porta está gasta. Ajustamos o sistema e trocamos a borracha de vedação para o vidro ficar limpo e as garrafas bem visíveis.'],
      ['Vocês instalam e atendem adega residencial também?', 'Sim. Atendemos adegas comerciais (restaurantes, bares, adegas) e residenciais, de garrafeiras a expositores de grande capacidade, com instalação nivelada, regulagem e garantia no serviço.'],
    ],
  },

  'maquina-de-gelo': {
    slug: 'maquina-de-gelo',
    title: 'Máquina de gelo',
    icon: 'snowflake',
    eyebrow: 'Máquina de gelo',
    metaTitle: 'Conserto de máquina de gelo no Rio | Santos Refrigeração',
    metaDescription: 'Conserto, manutenção e instalação de máquinas de gelo para bares, restaurantes e comércios no Rio e Grande Rio. Gelo na hora, sem faltar. Orçamento sem compromisso.',
    heroTitle: 'Conserto e manutenção de máquina de gelo no Rio e Grande Rio',
    highlight: 'máquina de gelo',
    heroLead: 'Faltar gelo no movimento é prejuízo certo. Fazemos instalação, manutenção preventiva e corretiva e conserto de máquinas de gelo de bares, restaurantes, hotéis e comércios, garantindo produção constante e gelo bem formado em todo o Rio e Grande Rio.',
    heroImageLabel: 'Foto da máquina de gelo / serviço',
    servicesTitle: 'Máquina de gelo produzindo sem parar',
    intro: [
      'A máquina de gelo depende de três sistemas em harmonia: refrigeração, água e ciclo de produção/colheita. A qualidade da água e a limpeza interna afetam diretamente o formato e a transparência do gelo. Fazemos a instalação com avaliação do ponto de água e energia e a regulagem do ciclo de produção.',
      'Na manutenção preventiva limpamos e higienizamos o sistema (fundamental por produzir gelo para consumo), verificamos a carga de gás, testamos o compressor, o sistema de água e o filtro, e ajustamos o ciclo de produção e colheita. Máquina limpa produz mais, com gelo firme e transparente.',
      'Na corretiva resolvemos máquina que produz pouco gelo, gelo mal formado, que trava no meio do ciclo, com ruído ou vazamento — com troca de compressor, recarga de gás, reparo do sistema de água, filtro e parte elétrica. Diagnóstico e preço fechado antes de começar, com garantia no reparo.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Instalação de máquina de gelo',
      'Manutenção preventiva programada',
      'Manutenção corretiva de emergência',
      'Troca de compressor',
      'Recarga e reparo de vazamento de gás',
      'Limpeza e higienização do sistema',
      'Reparo do sistema de água e troca de filtro',
      'Ajuste do ciclo de produção e colheita',
      'Reparo da bomba e da válvula de água',
      'Reparo de parte elétrica',
      'Ajuste e calibração de temperatura',
      'Contrato de manutenção regular',
    ],
    signsTitle: 'Sinais de que a máquina de gelo precisa de atenção',
    signs: [
      ['thermometer-sun', 'Produz pouco gelo', 'A produção cai e não dá conta do movimento.'],
      ['droplets', 'Gelo mal formado', 'Pedras moles, ocas ou pequenas indicam falha no ciclo.'],
      ['alert-triangle', 'Para no meio do ciclo', 'A máquina trava ou desliga durante a produção.'],
      ['volume-2', 'Ruído no motor', 'Barulho fora do normal é sinal de desgaste.'],
      ['zap', 'Conta de luz alta', 'Consumo elevado costuma ser condensador sujo ou gás baixo.'],
      ['filter', 'Gelo com gosto ou turvo', 'Água mal filtrada deixa o gelo turvo ou com sabor.'],
    ],
    ctaTitle: 'Sua máquina de gelo parou? Fale conosco agora.',
    waMessage: 'Olá! Preciso de atendimento para MÁQUINA DE GELO. Podem me passar um orçamento?',
    faqTitle: 'Dúvidas sobre máquina de gelo',
    faq: [
      ['A máquina está produzindo pouco gelo. Por quê?', 'As causas comuns são gás baixo por vazamento, condensador sujo, filtro de água entupido ou ciclo de produção desregulado. Fazemos o diagnóstico completo e corrigimos a causa para a produção voltar ao normal.'],
      ['O gelo está saindo mole ou oco. É problema?', 'Sim, indica falha no ciclo de produção/colheita, gás baixo ou problema na água. Ajustamos o ciclo e verificamos a refrigeração e o sistema de água para o gelo voltar a sair firme.'],
      ['Preciso limpar a máquina de gelo com que frequência?', 'Como produz gelo para consumo, a higienização deve ser periódica e regular, junto com a troca do filtro de água. Isso garante gelo transparente, sem gosto, e evita a queda de produção.'],
      ['O gelo está com gosto ou turvo. O que fazer?', 'Normalmente é a qualidade da água ou o filtro saturado. Fazemos a higienização do sistema e a troca do filtro, deixando o gelo transparente e sem sabor.'],
    ],
  },

  'tubulacao-ar-condicionado': {
    slug: 'tubulacao-ar-condicionado',
    title: 'Tubulação de ar condicionado',
    icon: 'git-branch',
    eyebrow: 'Tubulação de ar condicionado',
    metaTitle: 'Tubulação de ar condicionado no Rio | Santos Refrigeração',
    metaDescription: 'Projeto e instalação de tubulação de ar condicionado no Rio de Janeiro e Grande Rio: tubulação de cobre, dreno e infraestrutura para split e VRF. Orçamento sem compromisso.',
    heroTitle: 'Tubulação de ar condicionado no Rio de Janeiro e Grande Rio',
    highlight: 'tubulação',
    heroLead: 'A tubulação é a parte da instalação que ninguém vê e que define o desempenho do ar condicionado pelos próximos anos. Executamos o projeto e a passagem da tubulação de cobre, o dreno e toda a infraestrutura de split, multi split e VRF em obras novas e reformas, no Rio de Janeiro e Grande Rio.',
    heroImageLabel: 'Tubulação de ar condicionado — serviço Santos Refrigeração',
    servicesTitle: 'Tubulação de ar condicionado feita para durar',
    intro: [
      'Toda instalação de ar condicionado começa pela infraestrutura. Definimos o trajeto entre a evaporadora e a condensadora, a bitola correta do tubo de cobre para a capacidade do equipamento, o isolamento térmico das linhas de sucção e líquido, e o caimento do dreno. Tubulação subdimensionada ou com trajeto longo demais reduz a capacidade de refrigeração e sobrecarrega o compressor, mesmo com o aparelho novo.',
      'Trabalhamos com tubo de cobre para refrigeração, solda com vareta de prata, isolamento em polietileno expandido e vácuo com bomba antes da carga de gás. O vácuo é a etapa mais negligenciada do mercado: umidade e ar dentro da linha reagem com o óleo do compressor e formam ácido, que corrói o sistema por dentro ao longo de meses. Também executamos o teste de estanqueidade com nitrogênio antes de liberar a linha.',
      'Atendemos obra nova, reforma e readequação de infraestrutura existente: passagem em shaft, forro, alvenaria ou aparente com acabamento em canaleta, além de prumadas para prédios comerciais e sistemas com várias evaporadoras. Você recebe o projeto e o preço fechado antes de começar.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Projeto de infraestrutura para ar condicionado',
      'Passagem de tubulação de cobre para split e multi split',
      'Tubulação para sistemas VRF e prumadas comerciais',
      'Dimensionamento de bitola conforme a capacidade (BTU)',
      'Isolamento térmico das linhas de sucção e líquido',
      'Solda com vareta de prata',
      'Instalação de dreno com caimento correto',
      'Teste de estanqueidade com nitrogênio',
      'Vácuo com bomba antes da carga de gás',
      'Tubulação embutida em alvenaria, forro ou shaft',
      'Tubulação aparente com acabamento em canaleta',
      'Readequação de infraestrutura existente',
      'Instalação de suportes e bases para condensadora',
      'Reparo de vazamento em linha de cobre',
    ],
    sections: [
      { title: 'Projeto e passagem de tubulação de cobre', body: [
        'A bitola do tubo é determinada pela capacidade do equipamento e pela distância entre as unidades. Um split de 12.000 BTU e um de 36.000 BTU não usam a mesma linha, e o erro nessa escolha aparece como perda de rendimento, não como defeito aparente — o aparelho liga, gela pouco e consome muito.',
        'Definimos o trajeto no início da obra, junto com a elétrica e a hidráulica, para que a tubulação passe embutida sem quebra posterior. Quando a obra já está pronta, avaliamos as opções de passagem aparente com o melhor acabamento possível.',
      ] },
      { title: 'Tubulação aparente ou embutida: qual escolher', body: [
        'A tubulação embutida em alvenaria ou forro desaparece visualmente e é a escolha natural em obra nova, desde que prevista antes do reboco. A contrapartida é o acesso: qualquer reparo futuro na linha exige abrir o revestimento.',
        'A tubulação aparente, com canaleta de PVC ou acabamento em alumínio, permite manutenção sem quebra e é a solução para instalações em imóvel pronto, locado ou tombado. Bem executada, com alinhamento e canaleta na cor do ambiente, tem acabamento discreto.',
      ] },
      { title: 'Dreno com caimento correto: o detalhe que evita vazamento', body: [
        'A evaporadora produz água por condensação, e essa água sai por gravidade. Sem caimento contínuo em toda a extensão do dreno, ela empoça dentro da linha, transborda pela bandeja e aparece como infiltração na parede ou pingando do aparelho — o defeito mais comum em instalação malfeita.',
        'Executamos o dreno com inclinação constante, sem trechos em nível ou contra-fluxo, com sifão quando o ponto de descarte exige, e testamos com água antes de fechar o forro. Também corrigimos drenos existentes que estão vazando.',
      ] },
      { title: 'Quanto custa a tubulação de ar condicionado', body: [
        'O valor depende da metragem de tubo, da bitola exigida pela capacidade do equipamento, do número de evaporadoras, do tipo de passagem (embutida, aparente, shaft) e da altura da prumada. Por isso não trabalhamos com tabela fechada.',
        'Fazemos a visita técnica, medimos o trajeto real e enviamos o orçamento com material e mão de obra discriminados, antes de qualquer serviço. Sem surpresa na conta.',
      ] },
    ],
    signsTitle: 'Sinais de tubulação mal executada',
    signs: [
      ['droplets', 'Pingando ou infiltrando', 'Água escorrendo do aparelho ou mancha na parede é dreno sem caimento.'],
      ['thermometer-sun', 'Gela pouco desde o primeiro dia', 'Aparelho novo que não rende costuma ser bitola errada ou linha longa demais.'],
      ['zap', 'Consumo acima do esperado', 'Linha sem isolamento faz o compressor trabalhar mais para o mesmo resultado.'],
      ['snowflake', 'Gelo na tubulação', 'Formação de gelo no tubo indica isolamento rompido ou carga de gás incorreta.'],
      ['wind', 'Gás acabando com frequência', 'Recarga repetida significa vazamento na linha, não consumo normal.'],
      ['alert-triangle', 'Ruído de vibração na parede', 'Tubo sem fixação adequada transmite vibração para a estrutura.'],
    ],
    ctaTitle: 'Vai instalar ar condicionado? Comece pela tubulação certa.',
    waMessage: 'Olá! Preciso de orçamento para TUBULAÇÃO DE AR CONDICIONADO. Podem me atender?',
    faqTitle: 'Dúvidas sobre tubulação de ar condicionado',
    faq: [
      ['Vocês fazem só a tubulação ou a instalação completa?', 'Fazemos as duas. Podemos executar apenas a infraestrutura — tubulação de cobre, dreno, elétrica e suportes — para o equipamento ser instalado depois, ou a instalação completa com vácuo, carga de gás e start-up. Muita obra contrata a infraestrutura na fase de alvenaria e o equipamento meses depois.'],
      ['Vocês vendem o tubo de cobre?', 'Somos empresa de serviço, não de material. Fornecemos o tubo e os insumos dentro do orçamento da obra, com a bitola correta para o seu equipamento, mas não trabalhamos com venda de tubo avulso.'],
      ['Qual a distância máxima entre a evaporadora e a condensadora?', 'Depende do modelo. Cada fabricante especifica o comprimento máximo de linha e o desnível permitido, e passar desse limite exige carga adicional de gás ou inviabiliza o trajeto. Verificamos a especificação do seu equipamento antes de definir o percurso.'],
      ['Dá para passar tubulação em imóvel já pronto, sem quebrar?', 'Na maioria dos casos, sim — com passagem aparente em canaleta, por forro ou por shaft existente. Avaliamos o imóvel e apresentamos as opções com o acabamento de cada uma antes de você decidir.'],
      ['O que é o vácuo e por que ele importa?', 'É a retirada do ar e da umidade de dentro da tubulação com bomba, antes da carga de gás. Sem isso, a umidade reage com o óleo do compressor e forma ácido, que corrói o sistema por dentro ao longo de meses. É a etapa mais pulada do mercado e uma das principais causas de compressor queimado em aparelho novo.'],
    ],
  },

  'higienizacao-ar-condicionado': {
    slug: 'higienizacao-ar-condicionado',
    title: 'Higienização de ar condicionado',
    icon: 'spray-can',
    eyebrow: 'Higienização de ar condicionado',
    metaTitle: 'Higienização de ar condicionado no Rio | Santos Refrigeração',
    metaDescription: 'Higienização e limpeza de ar condicionado no Rio de Janeiro e Grande Rio: filtros, serpentina e turbina. Para comércio, escritório e residência. Orçamento sem compromisso.',
    heroTitle: 'Higienização de ar condicionado no Rio de Janeiro e Grande Rio',
    highlight: 'higienização',
    heroLead: 'O ar condicionado recircula o mesmo ar do ambiente várias vezes por hora. Tudo que fica retido na serpentina e na turbina volta para quem está na sala. Fazemos a higienização técnica completa — filtros, serpentina, turbina, bandeja e dreno — em comércio, escritório e residência no Rio de Janeiro e Grande Rio.',
    heroImageLabel: 'Higienização de ar condicionado — serviço Santos Refrigeração',
    servicesTitle: 'Higienização completa, não só troca de filtro',
    intro: [
      'Limpar o filtro é manutenção de usuário e resolve pouco. A sujeira que causa cheiro e reduz o rendimento fica depois dele: na serpentina da evaporadora, nas pás da turbina, na bandeja de condensado e no dreno. Nossa higienização desmonta o conjunto, lava essas partes com produto específico para alumínio e remove o biofilme que se forma na umidade permanente do equipamento.',
      'O processo inclui isolamento da área com bolsa coletora, retirada e lavagem dos filtros, aplicação de químico na serpentina, limpeza mecânica da turbina, desobstrução do dreno, higienização da bandeja e limpeza da condensadora externa. Ao final medimos temperatura de insuflamento e retorno para confirmar o ganho de rendimento.',
      'Serpentina obstruída reduz a troca térmica: o aparelho gela menos e o compressor fica mais tempo ligado para chegar à mesma temperatura, o que aparece direto na conta de luz. A higienização periódica é, ao mesmo tempo, questão de qualidade do ar e de consumo. Atendemos unidade isolada e parque de equipamentos com visita programada.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Higienização completa de split e multi split',
      'Lavagem técnica da serpentina da evaporadora',
      'Limpeza mecânica da turbina e do rotor',
      'Retirada, lavagem e recolocação dos filtros',
      'Higienização da bandeja de condensado',
      'Desobstrução e sanitização do dreno',
      'Limpeza da unidade condensadora externa',
      'Aplicação de bactericida e fungicida',
      'Higienização de ar condicionado de janela',
      'Limpeza de cassete e piso-teto',
      'Medição de temperatura antes e depois',
      'Contrato de higienização programada',
      'Higienização para escritório e loja',
      'Atendimento a parque de equipamentos',
    ],
    sections: [
      { title: 'Por que higienizar: mofo, cheiro e qualidade do ar', body: [
        'A evaporadora trabalha permanentemente úmida por causa da condensação. Somada à poeira que passa pelo filtro, essa umidade forma um meio onde mofo e bactéria se instalam na serpentina e na bandeja. O cheiro característico ao ligar o aparelho é o sinal mais direto disso — não é o gás, é matéria orgânica na serpentina.',
        'Como o equipamento recircula o ar do ambiente, o que está retido ali é redistribuído continuamente. Em escritório e loja, onde as pessoas passam o dia inteiro com as janelas fechadas, isso costuma aparecer como irritação nas vias respiratórias e queixa recorrente de ar pesado.',
      ] },
      { title: 'Como fazemos: filtros, serpentina e turbina', body: [
        'Isolamos a área com bolsa coletora para a água de lavagem não cair no ambiente. Retiramos e lavamos os filtros, aplicamos químico específico para alumínio na serpentina e enxaguamos com pressão controlada — pressão alta amassa as aletas e reduz a troca térmica de forma permanente.',
        'A turbina é limpa mecanicamente, pá por pá: é onde a sujeira mais se acumula e onde a limpeza superficial não chega. Depois desobstruímos o dreno, higienizamos a bandeja, limpamos a condensadora externa e medimos a temperatura de insuflamento para comprovar o resultado.',
      ] },
      { title: 'De quanto em quanto tempo higienizar', body: [
        'Para residência com uso moderado, uma higienização por ano costuma ser suficiente. Em escritório e loja, com o equipamento ligado o dia inteiro, o intervalo cai para seis meses. Cozinha, academia, salão e ambiente com muita circulação de pessoas pedem intervalos menores, porque gordura e poeira saturam a serpentina mais rápido.',
        'Um indicador prático: se o aparelho está gelando menos do que gelava, ou se sai cheiro ao ligar, o intervalo já passou.',
      ] },
      { title: 'Higienização para comércio, escritório e residência', body: [
        'Em comércio e escritório trabalhamos com visita programada e horário combinado — fora do expediente quando necessário — e atendemos parque de equipamentos com relatório por unidade. Contrato de higienização periódica sai mais barato que atendimento avulso e evita a queda de rendimento no verão, quando o equipamento é mais exigido.',
        'Em residência atendemos split, janela, cassete e piso-teto, com proteção de móveis e piso e limpeza da área ao final.',
      ] },
    ],
    signsTitle: 'Sinais de que a higienização está atrasada',
    signs: [
      ['wind', 'Cheiro ao ligar', 'Odor de mofo vindo do aparelho é matéria orgânica na serpentina.'],
      ['thermometer-sun', 'Gelando menos que antes', 'Serpentina obstruída reduz a troca térmica e o rendimento.'],
      ['zap', 'Conta de luz subindo', 'Aparelho sujo fica mais tempo ligado para atingir a mesma temperatura.'],
      ['droplets', 'Pingando dentro do ambiente', 'Bandeja e dreno entupidos fazem a água transbordar.'],
      ['volume-2', 'Ruído novo na evaporadora', 'Sujeira acumulada na turbina desbalanceia o rotor.'],
      ['alert-triangle', 'Queixa de ar pesado', 'Irritação respiratória recorrente em ambiente fechado e climatizado.'],
    ],
    ctaTitle: 'Ar condicionado com cheiro ou gelando pouco? Agende a higienização.',
    waMessage: 'Olá! Preciso de HIGIENIZAÇÃO DE AR CONDICIONADO. Podem me passar um orçamento?',
    faqTitle: 'Dúvidas sobre higienização de ar condicionado',
    faq: [
      ['Vocês fazem higienização de ar condicionado automotivo?', 'Não. Trabalhamos com ar condicionado de ambiente — split, multi split, janela, cassete e piso-teto — em comércio, escritório e residência. Higienização de ar condicionado de carro é serviço automotivo, com equipamento e acesso completamente diferentes, e não faz parte do nosso escopo.'],
      ['Qual a diferença entre limpar o filtro e higienizar?', 'Lavar o filtro é manutenção de usuário e remove só a poeira da superfície. A higienização desmonta o conjunto e trata o que está atrás do filtro: serpentina, turbina, bandeja e dreno. É ali que se forma o biofilme responsável pelo cheiro e pela queda de rendimento — e é a parte que a limpeza doméstica não alcança.'],
      ['Quanto tempo demora e preciso desligar o ambiente?', 'Uma unidade split leva em média de uma a duas horas, dependendo do grau de sujeira e do acesso. Trabalhamos com bolsa coletora e proteção de piso e móveis, então o ambiente continua utilizável ao redor. Em loja e escritório podemos agendar fora do horário de funcionamento.'],
      ['A higienização reduz a conta de luz?', 'Costuma reduzir. Serpentina obstruída diminui a troca térmica, e o compressor precisa ficar mais tempo ligado para chegar à temperatura configurada. Medimos a temperatura de insuflamento antes e depois, o que dá para ver o ganho de rendimento na prática.'],
      ['Vocês atendem vários aparelhos de uma vez?', 'Sim. Atendemos parque de equipamentos com visita programada e relatório por unidade, e trabalhamos com contrato de higienização periódica para comércio, escritório, clínica e condomínio.'],
    ],
  },

  'tecnico-refrigeracao-comercial': {
    slug: 'tecnico-refrigeracao-comercial',
    title: 'Técnico de refrigeração',
    icon: 'wrench',
    eyebrow: 'Assistência técnica',
    metaTitle: 'Técnico de refrigeração no Rio de Janeiro | Santos Refrigeração',
    metaDescription: 'Técnico de refrigeração comercial no Rio de Janeiro e Grande Rio. Assistência técnica, manutenção e conserto de câmara fria, chopeira, ar condicionado e geladeira. Orçamento sem compromisso.',
    heroTitle: 'Técnico de refrigeração comercial no Rio de Janeiro',
    highlight: 'refrigeração',
    heroLead: 'Somos uma empresa de refrigeração e climatização com doze anos de atendimento no Rio de Janeiro e Grande Rio. Assistência técnica em câmara fria, chopeira, ar condicionado, geladeira comercial, balcão, freezer e máquina de gelo — com diagnóstico e preço fechado antes de começar o serviço.',
    heroImageLabel: 'Técnico de refrigeração Santos Refrigeração em atendimento',
    servicesTitle: 'Serviço de refrigeração para quem não pode parar',
    intro: [
      'Equipamento de refrigeração parado em estabelecimento comercial não é inconveniente, é prejuízo em curso: estoque perdido, venda interrompida e cliente que vai embora. Por isso nosso atendimento é organizado em torno do diagnóstico rápido — identificar a causa real na primeira visita e resolver, em vez de trocar peça por tentativa.',
      'Atendemos manutenção corretiva, manutenção preventiva programada e instalação, em equipamentos comerciais e industriais de qualquer marca. O técnico chega com instrumento de medição, não só com chave: medimos pressão de alta e baixa, superaquecimento, sub-resfriamento e corrente do compressor. Sintoma igual pode ter causa diferente, e é a medição que separa uma da outra.',
      'Trabalhamos com bar, restaurante, padaria, mercado, açougue, distribuidora, lanchonete, hotel, clínica e escritório. Para operações que não podem ter parada, oferecemos contrato de manutenção com visitas programadas — sai mais barato que o atendimento de emergência e evita a quebra no pior momento.',
    ],
    servicesListTitle: 'Nossos serviços',
    services: [
      'Assistência técnica em refrigeração comercial',
      'Manutenção corretiva de emergência',
      'Manutenção preventiva programada',
      'Contrato de manutenção para empresas',
      'Diagnóstico técnico com medição de pressão',
      'Recarga e troca de gás refrigerante',
      'Caça a vazamento com detector eletrônico',
      'Troca de compressor e componentes',
      'Reparo de parte elétrica e quadro de comando',
      'Substituição de termostato e controlador digital',
      'Refrigeração e climatização comercial',
      'Instalação de equipamentos novos',
      'Atendimento a equipamentos de qualquer marca',
      'Laudo técnico para seguro e garantia',
    ],
    sections: [
      { title: 'Assistência técnica em refrigeração para o seu negócio', body: [
        'Um técnico de refrigeração não conserta aparelho, conserta sistema. O mesmo sintoma — não gela — pode ser gás baixo por vazamento, condensador sujo, compressor com baixo rendimento, válvula de expansão obstruída ou parâmetro errado no controlador. Trocar peça sem medir resolve por alguns dias e o problema volta.',
        'Nosso atendimento parte da medição: pressão de alta e baixa, superaquecimento, sub-resfriamento e corrente do compressor. Com esses números se sabe onde está a falha. Só então apresentamos o diagnóstico e o preço fechado, para você aprovar antes de qualquer serviço.',
      ] },
      { title: 'Como funciona o atendimento', body: [
        'Você entra em contato pelo WhatsApp ou telefone descrevendo o equipamento e o sintoma. Fazemos uma triagem inicial nessa conversa, porque parte dos casos se resolve em orientação — equipamento no modo errado, disjuntor desarmado, dreno entupido — e não vale uma visita.',
        'Confirmada a necessidade, agendamos a visita técnica. O técnico faz o diagnóstico no local, apresenta o que foi encontrado e o valor fechado do reparo. Aprovado, na maioria dos casos resolvemos na mesma visita; quando depende de peça específica, informamos o prazo antes. Todo serviço tem garantia.',
      ] },
      { title: 'Área de atendimento', body: [
        'Atendemos a cidade do Rio de Janeiro e o Grande Rio: Zona Norte, Zona Oeste, Zona Sul, Centro, Baixada Fluminense, Niterói e São Gonçalo. Nossa base fica em Cascadura, na Av. Dom Hélder Câmara.',
        'O horário de atendimento é de segunda a sábado, das 8h às 18h. Para contratos de manutenção, as visitas são programadas em calendário combinado com o cliente.',
      ] },
    ],
    hubTitle: 'Equipamentos que atendemos',
    hubLinks: [
      ['Câmara fria', 'camara-fria.html', 'warehouse', 'Instalação, manutenção e conserto de câmara frigorífica.'],
      ['Chopeiras', 'chopeiras.html', 'beer', 'Instalação, manutenção e higienização do sistema de tiragem.'],
      ['Ar condicionado', 'ar-condicionado.html', 'air-vent', 'Instalação, manutenção, higienização e tubulação.'],
      ['Geladeira comercial', 'geladeira-comercial.html', 'refrigerator', 'Conserto e manutenção de geladeira e refrigerador comercial.'],
      ['Balcão refrigerado', 'balcao-refrigerado.html', 'store', 'Conserto e manutenção de balcões e expositores.'],
      ['Ilha de congelados', 'ilha-de-congelados.html', 'package', 'Conserto e manutenção de ilhas e expositores de congelados.'],
      ['Ultra freezer', 'ultra-freezer.html', 'snowflake', 'Conserto e manutenção de equipamentos de baixa temperatura.'],
      ['Máquina de gelo', 'maquina-de-gelo.html', 'cuboid', 'Conserto, manutenção e higienização de máquinas de gelo.'],
      ['Refresqueira', 'refresqueira.html', 'cup-soda', 'Conserto e manutenção de refresqueiras.'],
      ['Gela Caneca', 'gela-caneca.html', 'glass-water', 'Manutenção e conserto de gela caneca.'],
      ['Adega climatizada', 'adega-vinhos.html', 'wine', 'Instalação e manutenção de adegas climatizadas de vinhos.'],
    ],
    signsTitle: 'Quando chamar um técnico de refrigeração',
    signs: [
      ['thermometer-sun', 'Não atinge a temperatura', 'Equipamento ligado que não chega ao ponto configurado.'],
      ['zap', 'Conta de luz fora do padrão', 'Salto no consumo sem mudança de operação indica perda de eficiência.'],
      ['volume-2', 'Ruído novo no motor', 'Barulho que não existia antes costuma ser desgaste mecânico.'],
      ['wind', 'Gás acabando sempre', 'Recarga frequente é vazamento, não consumo normal.'],
      ['alert-triangle', 'Desarmando sozinho', 'Desligamento repetido é proteção atuando contra sobrecarga.'],
      ['snowflake', 'Gelo em excesso', 'Acúmulo anormal de gelo aponta falha de degelo, dreno ou vedação.'],
    ],
    ctaTitle: 'Precisa de um técnico de refrigeração hoje?',
    waMessage: 'Olá! Preciso de um TÉCNICO DE REFRIGERAÇÃO. Podem me atender?',
    faqTitle: 'Dúvidas sobre assistência técnica em refrigeração',
    faq: [
      ['Vocês atendem equipamento de qualquer marca?', 'Sim. Trabalhamos com equipamentos comerciais e industriais de refrigeração de todas as marcas, incluindo os fora de linha e sem assistência autorizada na região. O que define o reparo é o sistema — compressor, condensador, evaporador, gás e controle — não o fabricante.'],
      ['Quanto custa a visita técnica?', 'Cobramos a visita de diagnóstico, e o valor é abatido do serviço caso o reparo seja aprovado. Passamos o valor no primeiro contato, antes de agendar. Parte dos casos se resolve na própria triagem por WhatsApp, sem visita.'],
      ['Em quanto tempo vocês atendem?', 'Trabalhamos com atendimento ágil e priorizamos equipamento parado em operação comercial, onde há perda de estoque ou de faturamento. O prazo depende da agenda do dia e da região; informamos no momento do contato. Nosso horário é de segunda a sábado, das 8h às 18h.'],
      ['Vale mais a pena consertar ou trocar o equipamento?', 'Depende da idade do equipamento, do custo do reparo e do histórico de falhas. Compressor queimado em equipamento antigo, com outros componentes no fim da vida útil, muitas vezes não compensa. Apresentamos o diagnóstico com o custo real do reparo para você decidir com número na mão — não empurramos serviço.'],
      ['Vocês fazem contrato de manutenção mensal?', 'Sim, com visitas programadas e escopo definido por equipamento. É a modalidade indicada para quem não pode ter parada: sai mais barato que o atendimento de emergência avulso e antecipa a falha antes de ela acontecer no horário de pico.'],
      ['Vocês oferecem curso ou vaga de técnico de refrigeração?', 'Não. Somos empresa de serviço e atendemos clientes com equipamento a instalar ou reparar. Não ministramos curso de refrigeração nem estamos com processo seletivo aberto por esta página.'],
    ],
  },
};
